#
# Module manifest for module 'tcs.azure'
#
# Generated by: Nigel Tatschner
#
# Generated on: 05/08/2024
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '0.0.1'

GUID = '9d6151da-f9cf-4606-a985-d3f5c463d419'

Author = 'Nigel Tatschner'

CompanyName = 'Rothesay'

Copyright = '(c) 2024 Nigel Tatschner. All rights reserved.'

Description = 'Helper Functions for Microsoft Azure'

PowerShellVersion = '5.1'

RequiredModules = @('tcs.core')

NestedModules = @('tcs.azure.psm1')

FunctionsToExport = @(
    'New-IntuneAppGroup',
    'New-TcsDepartmentalGroup'
)

CmdletsToExport = @()

VariablesToExport = @()

AliasesToExport = @()

PrivateData = @{

    PSData = @{

        Tags = @("azure", "intune", "microsoft", "groups")

        ReleaseNotes = 'Adding helper functions for Intune App Groups.'

        ExternalModuleDependencies = @('Microsoft.Graph.Entra')

    }

}

}
