#
# Module manifest for module 'tcs.azure'
#
# Generated by: Nigel Tatschner
#
# Generated on: 05/08/2024
#

@{
    RootModule           = 'tcs.azure.psm1'
    ModuleVersion        = '0.2.0'
    GUID                 = '9d6151da-f9cf-4606-a985-d3f5c463d419'
    Author               = 'Nigel Tatschner'
    CompanyName          = 'TheCodeSaiyan'
    Copyright            = '(c) 2024-2026 Nigel Tatschner. All rights reserved.'
    Description          = 'Helper functions for Microsoft Azure and Microsoft Entra ID: naming departmental groups and creating Intune app assignment groups.'
    CompatiblePSEditions = @('Desktop', 'Core')
    PowerShellVersion    = '5.1'
    RequiredModules      = @(
        @{ ModuleName = 'tcs.core'; ModuleVersion = '0.3.0' }
    )
    FunctionsToExport    = @(
        'Get-DepartmentalGroupName',
        'New-IntuneAppGroup'
    )
    CmdletsToExport      = @()
    VariablesToExport    = @()
    AliasesToExport      = @('New-TcsDepartmentalGroup')
    PrivateData          = @{
        PSData = @{
            Tags                       = @('Azure', 'Entra', 'EntraID', 'Intune', 'Microsoft', 'Groups', 'PSEdition_Desktop', 'PSEdition_Core', 'Windows', 'Linux', 'MacOS')
            ProjectUri                 = 'https://github.com/ntatschner/TheCodeSaiyan-PowerShell-tcs.azure'
            LicenseUri                 = 'https://github.com/ntatschner/TheCodeSaiyan-PowerShell-tcs.azure/blob/main/LICENSE'
            ReleaseNotes               = 'https://github.com/ntatschner/TheCodeSaiyan-PowerShell-tcs.azure/blob/main/CHANGELOG.md'
            # New-IntuneAppGroup needs the Microsoft Entra PowerShell groups module at run time
            ExternalModuleDependencies = @('Microsoft.Entra.Groups')
        }
    }
}
